identifier_name:
  allowed_symbols: "_"
  validates_start_with_lowercase: false
  min_length: 1

class_name:
  allowed_symbols: "_"
  validates_start_with_lowercase: false

disabled_rules:
  - trailing_whitespace
  - line_length
  - opening_brace

opt_in_rules:
  - empty_count

line_length: 120
